/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.ly.java.thrift.inflectServer;

import javax.annotation.Generated;

@SuppressWarnings({ "cast", "rawtypes", "serial", "unchecked" })
@Generated(value = "Autogenerated by Thrift Compiler (0.9.2)", date = "2016-12-16")
public class HelloWorld {

	public interface Iface {

		public String sayHello(String username) throws org.apache.thrift.TException;

	}

	public interface AsyncIface {

		public void sayHello(String username, org.apache.thrift.async.AsyncMethodCallback resultHandler)
				throws org.apache.thrift.TException;

	}

}
