/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.ly.java.thrift.inflectServer4;

import javax.annotation.Generated;

@SuppressWarnings({ "cast", "rawtypes", "serial", "unchecked", "restriction" })
@Generated(value = "Autogenerated by Thrift Compiler (0.9.2)", date = "2016-12-30")
public class BaseServer {







}
